namespace MemoryMosaic.Models;

///Represents any kind of photo/video file.
public abstract class Media
{
	///The path to where the item is located, relative to a folder like mm_library or mm_import.
	public string Path { get; set; } = null!;
	
	public bool Starred { get; set; }
	
	public Guid Id { get; init; }

	///A compressed base64 string generated by ffmpeg. For videos, it stores the very first frame.
	public string Thumbnail { get; init; } = null!;
	
	public string? Description { get; set; }
	
	public bool Video { get; protected init; }

	public abstract string RequestPath { get; }
}