namespace MemoryMosaic.Models;

///Represents any kind of photo/video file.
public abstract class Media
{
	///The path to where the item is located, relative to a folder like mm_library or mm_import.
	public string Path { get; set; } = "";

	public Guid Id { get; protected init; }

	public bool Starred { get; set; }

	public string? Description { get; set; }

	public double? Latitude { get; set; }

	public double? Longitude { get; set; }

	///A compressed base64 string generated by FFmpeg. For videos, it stores the very first frame.
	public string Thumbnail { get; set; } = "";

	public bool Video { get; protected init; }

	///How many bytes this item is on disk.
	public long Size { get; protected init; }

	public abstract string RequestPath { get; }

	public abstract string FullPath { get; }
}