namespace PSS.Backend;

///Represents an item that is pending uploading in Import.razor.
public class ImportFile
{
	///The original filename of this item.
	public string originalFilename;

	///Tracks what the user has updated the filename to, if applicable.
	public string renamedFilename;

	///The file extension of the item.
	public string extension;

	///The path relative to pss_upload of this item. Contains 'pss_upload' at the front.
	public string shortPath;

	///The absolute path to the file to upload.
	public string fullPath;

	///null for images; otherwise a base64 string for video files that contains a compressed thumbnail of the first frame of the video, generated by ffmpepg.
	public string thumbnail;

	///If this item is already in pss_library.
	public bool alreadyInLib; //TODO: idk if this will be needed

	///The date and time this image or video was captured. null if this item doesnt have this data or the user removed it in Import.razor.
	public DateTime? dateTaken;

	///Where the date taken data came from (Filename, Metadata, or None).
	public D.DateTakenSrc dateTakenSrc;

	///The uuid of the item, which will be added to the database upon upload.
	public Guid uuid; //TODO: idk if this will be needed
}