DROP TABLE IF EXISTS media CASCADE;
DROP TABLE IF EXISTS media_trash CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS album_entries CASCADE;
DROP TABLE IF EXISTS album_entries_trash CASCADE;